@startuml visibruit
state 企業{
    [*] --> ログイン画面
    ログイン画面 : ログイン
    ログイン画面 --> パスワード変更画面
    パスワード変更画面 : パスワード変更
    ログイン画面 --> 企業トップページ
    企業トップページ : ヴィジブルートからのお知らせ

    企業ES修行部屋画面 : ES修行部屋一覧取得
    企業ES修行部屋画面 --> 学生閲覧画面     

}

state 学生{
    [*] --> 学生ログイン画面
    学生ログイン画面 : ログイン
    学生ログイン画面 --> 学生トップ画面
    学生トップ画面 : ポイント取得
    学生トップ画面 : 写真表示/アップロード
    学生トップ画面 : プロフィール取得
    学生トップ画面 : プロフィール更新
    学生トップ画面 : ガクチカ取得
    学生トップ画面 : ガクチカ更新
    学生トップ画面 : 自己PR取得
    学生トップ画面 : 自己PR更新
    学生トップ画面 : 自由記述取得
    学生トップ画面 : 自由記述更新
    学生トップ画面 : 志向性・希望条件情報取得
    学生トップ画面 : 志向性・希望条件情報更新
    学生トップ画面 --> デイリークエスト : デイリークエストボタン押下
    デイリークエスト質問画面 : デイリークエスト質問取得
    デイリークエスト質問画面 : デイリークエスト解答登録
    デイリークエスト質問画面 : ニュース取得
    デイリークエスト質問問題 : 感想更新
    デイリークエスト質問画面 --> デイリークエスト回答画面 : 解答送信ボタン押下
    デイリークエスト回答画面 : デイリークエスト回答取得
    デイリークエスト回答画面 : デイリークエストポイント取得
    デイリークエスト質問画面 --> デイリークエスト分析画面 : 過去の回答・分析押下
    デイリークエスト回答画面 --> デイリークエスト分析画面 : 過去の回答・分析押下
    デイリークエスト分析画面 : TBD
    学生トップ画面 --> ES修行部屋トップ画面
    ES修行部屋トップ画面 : TBD
    ES修行部屋トップ画面 --> ES修行部屋入力画面
    ES修行部屋入力画面 : ガクチカ取得
    ES修行部屋入力画面 : 自己PR取得
    ES修行部屋入力画面 : ガクチカ/自己PR公開


    学生トップ画面 --> スカウトメール
    学生トップ画面 --> 通知
}

state 共通 {
    企業ES修行部屋画面 --> ES修行部屋詳細画面
    ES修行部屋入力画面 --> ES修行部屋詳細画面 : 公開押下
    ES修行部屋トップ画面 --> ES修行部屋詳細画面 : 公開内容押下
    ES修行部屋詳細画面 : ES修行部屋コメント取得
    ES修行部屋詳細画面 : ES修行部屋コメント更新
    ES修行部屋詳細画面 : ES修行部屋いいね更新
    ES修行部屋詳細画面 : ES修行部屋ポイント贈与

}

state visibruit{

}

@enduml